# 7 days
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@nuxt/ui"
  - form-data@4.0.6
blockExoticSubdeps: true
# trustPolicy: no-downgrade
preferFrozenLockfile: true
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  vue-demi: true

overrides:
  "form-data@4": "^4.0.6"
