import { computed } from 'vue';
import { useLocalStorage } from '@vueuse/core';

const translations = {
  'zh-TW': {
    appTitle: 'Freqtrade UI',
    trade: '交易',
    dashboard: '儀表板',
    chart: '圖表',
    logs: '日誌',
    settings: '設定',
    backtest: '回測',
    downloadData: '下載資料',
    pairlistConfig: '交易對清單設定',
    logout: '登出',
    lockDynamicLayout: '鎖定動態版面',
    resetLayout: '重設版面',
    noBotSelected: '尚未選擇機器人',
    confirmDialogOff: '已停用確認對話框，強制平倉會立即執行，請小心。',
    version: '版本',
    toggleNightMode: '切換夜間模式',
    drawer: '抽屜選單',
    language: '語言',
    english: 'English',
    traditionalChinese: '繁體中文',
    autoRefresh: '自動重新整理',
    autoRefreshAllNow: '立即重新整理所有機器人',
    type: '類型',
    color: '顏色',
    lineChart: '折線圖',
    barChart: '柱狀圖',
    scatterChart: '散點圖',
    areaChartFillTo: '區域圖 - 填充到（留空則為折線圖）',
    scatterSymbolSize: '散點符號大小',
    uiSettings: '介面設定',
    chartSettings: '圖表設定',
    notificationSettings: '通知設定',
    backtestingSettings: '回測設定',
    botName: '機器人名稱',
    apiUrl: 'API 位址',
    username: '使用者名稱',
    password: '密碼',
    reset: '重設',
    cancel: '取消',
    submit: '送出',
    login: '登入',
    back: '返回',
    addNewBot: '新增機器人',
    loginToYourBot: '登入機器人',
    availableBotsTitle: '可用機器人',
    loginInfoExpired: '登入資訊已過期，請重新登入。',
    online: '線上',
    offline: '離線',
    logoutConfirmation: '登出確認',
    reallyRemoveBot: '確定要從 {{botName}}（{{botId}}）移除並登出嗎？',
    editBot: '編輯機器人',
    loginAgain: '重新登入',
    deleteBot: '刪除機器人',
    botNamePlaceholder: '機器人名稱',
    openTradesTitle: '未平倉交易',
    tradeHistoryTitle: '交易歷史',
    noOpenTrades: '目前沒有未平倉交易。',
    noClosedTradesSoFar: '目前還沒有已平倉交易。',
    openTradesHint: '顯示所有已選機器人的未平倉交易。點選交易可前往該交易/機器人的交易頁。',
    closedTradesHint: '顯示所有已選機器人的已平倉交易。點選交易可前往該交易/機器人的交易頁。',
    multiPane: '多區塊',
    pairsCombined: '交易對合併',
    general: '一般',
    performance: '績效',
    balance: '餘額',
    timeBreakdown: '時間分布',
    pairLocks: '交易對鎖定',
    pairlist: '交易對清單',
    openTradesTable: '未平倉交易',
    closedTradesTable: '已平倉交易',
    tradeDetail: '交易詳情',
    trades: '交易',
    noTradesToShow: '目前沒有可顯示的交易。',
    currentProfit: '目前獲利',
    closeProfit: '平倉獲利',
    currentRate: '目前價格',
    closeRate: '平倉價格',
    openRate: '開倉價格',
    amount: '數量',
    stakeAmount: '保證金',
    totalStakeAmount: '總保證金',
    openDate: '開倉時間',
    closeDate: '平倉時間',
    closeReason: '平倉原因',
    tradeId: '交易 ID',
    entryTag: '進場標籤',
    currentValue: '目前價值',
    positionValue: '倉位價值',
    realizedProfit: '已實現獲利',
    totalProfit: '總獲利',
    stoploss: '止損',
    atRisk: '風險金額',
    currentStoplossDistance: '目前止損距離',
    initialStoploss: '初始止損',
    stoplossLastUpdated: '止損最後更新',
    futuresMargin: '合約 / 保證金',
    direction: '方向',
    fundingFees: '資金費用',
    interestRate: '利率',
    liquidationPrice: '強平價格',
    orders: '訂單',
    remaining: '剩餘',
    filled: '已成交',
    openFees: '開倉手續費',
    closeFees: '平倉手續費',
    actions: '操作',
    closeActionsMenu: '關閉操作選單',
    forceExitTrade: '強制平倉',
    forceExitTradeLimit: '強制限價平倉',
    forceExitTradeMarket: '強制市價平倉',
    forceExitPartial: '部分平倉',
    cancelOpenOrders: '取消未成交訂單',
    increasePosition: '加碼倉位',
    reloadTrade: '重新載入',
    deleteTrade: '刪除交易',
    forceExitPosition: '平倉',
    forceEnterTrade: '強制開倉',
    orderDirection: '訂單方向',
    pair: '交易對',
    priceOptional: '價格［可選］',
    stakeAmountOptional: '保證金［可選］',
    leverageOptional: '槓桿［可選］',
    customEntryTagOptional: '自訂進場標籤［可選］',
    enterPosition: '開倉',
    exitPosition: '平倉',
    market: '市價',
    limit: '限價',
    long: '多',
    short: '空',
    all: '全部',
    details: '詳細資料',
    orderType: '訂單類型',
    currentlyOwning: '目前持有',
    estimatedValue: '估算價值',
    onlyAvailableWithLimitOrders: '僅限限價單使用',
    forceExitTradeQuestion: '確定要平掉交易 {{tradeId}}（{{pair}}）並使用 {{ordertype}} 訂單嗎？',
    deleteTradeQuestion: '確定要刪除交易 {{tradeId}}（{{pair}}）嗎？',
    cancelOpenOrderQuestion: '要取消交易 {{tradeId}}（{{pair}}）的未成交訂單嗎？',
    forceEnterTradeHeader: '強制開倉',
    increasingPositionFor: '為 {{pair}} 增加倉位',
    orderDirectionLongShort: '訂單方向（多 / 空）',
    runningFreqtrade: '正在執行 Freqtrade',
    runningWith: '以',
    on: '於',
    marketsWithStrategy: '市場運行，策略為',
    stoplossOnExchangeEnabled: '交易所止損已啟用',
    stoplossOnExchangeDisabled: '交易所止損已停用',
    currently: '目前狀態',
    forceEntryEnabled: '強制開倉：',
    dryRun: '模擬盤',
    live: '實盤',
    avgProfit: '平均獲利',
    bestPair: '最佳交易對',
    botStartDate: '機器人啟動時間',
    firstTradeOpened: '第一筆交易開啟時間',
    lastTradeOpened: '最後一筆交易開啟時間',
    profitFactor: '獲利因子',
    tradingVolume: '交易量',
    strategyParameters: '策略參數',
    botBalance: '機器人餘額',
    accountBalance: '帳戶餘額',
    showingBotBalance: '顯示機器人餘額',
    showingAccountBalance: '顯示帳戶餘額',
    hideSmallBalances: '隱藏小額餘額',
    showAllBalances: '顯示全部餘額',
    currency: '幣別',
    available: '可用',
    total: '總計',
    increaseOverInitialCapital: '相較於初始資本增加',
    totalLabel: '總計',
    entries: '進場',
    exits: '出場',
    mixTag: '混合標籤',
    profitPercent: '獲利 %',
    count: '數量',
    periodBreakdown: '週期分布',
    days: '日',
    weeks: '週',
    months: '月',
    breakdown: '分布',
    in: '於',
    profit: '獲利',
    absDollar: '絕對 $',
    relPercent: '相對 %',
    timePeriodChartOnlySingleBot: '時間週期圖表僅能在只選擇單一機器人且顯示絕對獲利時使用。',
    blacklistMethods: '黑名單方法',
    whitelist: '白名單',
    blacklist: '黑名單',
    addPairToBlacklist: '加入黑名單',
    selectPairsToDeleteFromBlacklist: '選取要從黑名單刪除的交易對。',
    deleteLock: '刪除鎖定',
    apiUrlRequired: '需要 API 位址',
    invalidPassword: '密碼無效',
    nameAndPasswordRequired: '需要名稱與密碼。',
    connectedLoginFailed: '已連上機器人，但登入失敗，使用者名稱或密碼錯誤。',
    loginFailed: '登入失敗。',
    loginFailedDetails:
      '請確認機器人正在執行、API 已啟用，且網址可連線。\n你可以前往 {{url}}/api/v1/ping 檢查機器人 API 是否可連線。',
    checkCorsConfig: '請另外確認機器人的 CORS 設定：',
    freqtradeCorsDocs: 'Freqtrade CORS 說明文件',
    showOpenTradesInHeader: '在頁首顯示未平倉倉位',
    utcTimezone: 'UTC 時區',
    backgroundSync: '背景同步',
    confirmDialogForTradeExits: '平倉時顯示確認對話框',
    showTextOnMultiPaneButtons: '在多分頁按鈕上顯示文字',
    chartScaleSide: '圖表刻度位置',
    left: '左側',
    right: '右側',
    useHeikinAshiCandles: '使用 Heikin Ashi K 線',
    onlyRequestNecessaryColumns: '只請求必要欄位',
    defaultCandlesToDisplay: '預設顯示的 K 棒數量',
    candleColorPreference: 'K 線顏色偏好',
    greenUpRedDown: '綠漲紅跌',
    greenDownRedUp: '綠跌紅漲',
    entryNotifications: '開倉通知',
    exitNotifications: '平倉通知',
    entryCancelNotifications: '開倉取消通知',
    exitCancelNotifications: '平倉取消通知',
    backtestingMetrics: '回測指標',
    selectMetricsByPairTag: '選擇要依照 pair / tag 顯示哪些指標。',
    backtesting: '回測',
    loadResults: '載入結果',
    runBacktest: '執行回測',
    analyzeResult: '分析結果',
    compareResults: '比較結果',
    visualizeSummary: '查看摘要圖表',
    visualizeResult: '查看結果圖表',
    backtestRunning: '回測進行中：',
    backtestingParameters: '回測參數',
    backtestingSummary: '回測摘要',
    webserverRequiredForBacktest: '機器人必須在 webserver 模式下才能使用回測。',
    loadFromString: '從字串載入',
    save: '儲存',
    show: '顯示',
    hide: '隱藏',
    availableBots: '可用機器人',
    openTrades: '未平倉倉位',
    tradeHistory: '交易歷史',
    noHistoricWalletData: '沒有可用的錢包歷史資料。',
    noPairSelected: '尚未選擇交易對',
    whitelistMethod: '白名單方法',
    blacklistUnavailable: '黑名單不可用。請先登入並確認伺服器正在執行。',
    listUnavailable: '清單不可用。請先登入並確認伺服器正在執行。',
    longEntrySignal: '多單開倉訊號',
    longExitSignal: '多單平倉訊號',
    shortEntrySignal: '空單開倉訊號',
    shortExitSignal: '空單平倉訊號',
    showPillInIcon: '在圖示上顯示徽章',
    showInTitle: '在標題列顯示',
    dontShowOpenTradesInHeader: '不在頁首顯示未平倉倉位',
    tradesLog: '交易紀錄',
    profitDistribution: '獲利分布',
    dailyProfit: '每日獲利',
    absoluteProfit: '絕對獲利',
    relativeProfit: '相對獲利',
    tradeCount: '交易數',
    hourlyProfit: '每小時獲利',
    marketChangePercent: '市場變化 %',
    winningTrades: '獲利交易',
    losingTrades: '虧損交易',
    tradesDurations: '交易持續時間',
    tradeDuration: '交易持續時間',
    backtestComparison: '回測結果比較',
    resultPerPair: '每個交易對的結果',
    resultPerEnterTag: '每個開倉標籤的結果',
    resultPerExitReason: '每個平倉原因的結果',
    resultsMixedTag: '混合標籤結果',
    min: '最小值',
    q1: '第一四分位數',
    median: '中位數',
    q3: '第三四分位數',
    max: '最大值',
    deleteResult: '刪除結果',
    deleteThisResult: '刪除這筆結果。',
    deleteThisResultFromUI: '從 UI 刪除這筆結果。',
    reload: '重新載入',
    refresh: '重新整理',
    copy: '複製',
    copied: '已複製！',
    selectPair: '選擇交易對',
    selectTimeframe: '選擇時間週期',
    timeframe: '時間週期',
    timerange: '時間範圍：',
    startDate: '開始日期',
    endDate: '結束日期',
    startDownload: '開始下載',
    add: '新增',
    homeWelcome: '歡迎使用 Freqtrade UI',
    homeDescription: '這個頁面可以讓你控制你的交易機器人。',
    homeFooter: '祝你玩得愉快 - Freqtrade 團隊敬上',
    error404Title: '404 錯誤。',
    error404Body: '糟糕，找不到你要看的頁面。',
    error404Back: '別擔心，你可以回到',
    mainPage: '主頁',
    tradeSignal: '交易訊號',
    botLoginHeader: '登入你的機器人',
    botLoginButton: '登入',
    botListExpired: '登入資訊已過期！',
    customExchange: '自訂交易所',
    currentExchange: '目前交易所：',
    strategy: '策略',
    useLiveData: '使用即時資料',
    settingsPanel: '設定',
    selectPairsToPlot: '選擇要繪製的交易對',
    refreshChart: '重新整理圖表',
    multiPair: '多交易對',
    showChartAreas: '顯示圖表區域',
    heikinAshi: 'Heikin Ashi',
    plotConfigurator: '圖表配置器',
    plotConfigName: '圖表設定',
    showTagsInTooltips: '在提示中顯示標籤',
    markAreaZIndex: '標記區域 Z 索引',
    targetPlot: '目標圖表',
    indicatorsInThisPlot: '此圖表的指標',
    noIndicatorsSelected: '尚未選擇指標',
    removeIndicatorToPlot: '從圖表移除指標',
    indicatorFromTemplate: '從範本載入指標',
    addIndicatorToPlot: '加入指標到圖表',
    selectIndicatorToAdd: '選擇要新增的指標',
    resetToLastSavedConfiguration: '重設為上次儲存的設定',
    fromStrategy: '從策略載入',
    showConfiguration: '顯示設定',
    hideConfiguration: '隱藏設定',
    saveConfiguration: '儲存設定',
    loadConfigurationFromTextBox: '從下方文字方塊載入設定',
    editThis: '編輯這個 {{name}}',
    duplicateThis: '複製這個 {{name}}',
    deleteThis: '刪除這個 {{name}}',
    addNewThis: '新增這個 {{name}}',
    abort: '取消',
    ok: '確定',
    noSelectedItem: '尚未選取項目',
    itemsSelected: '{0} 個項目已選取',
    defaultsTo: '預設為',
    notAvailableInThisChart: '此圖表中不可用',
    noStrategySelectedCannotLoadPlotConfig: '尚未選擇策略，無法載入圖表配置。',
    failedToLoadPlotConfigFromStrategy: '無法從策略載入圖表配置。',
    deleteThisValue: '刪除這個值',
    addNewValue: '新增值',
    deleteResultFromDisk: '要從磁碟刪除結果 {{filename}} 嗎？',
    refreshResults: '重新整理結果',
    filterResults: '篩選結果',
    loadHistoricResults: '從磁碟載入歷史結果。你可以點選多筆結果，一次載入到 freqUI。',
    strategyLabel: '策略',
    detailsLabel: '詳細資訊',
    backtestTime: '回測時間',
    filename: '檔案名稱',
    loadThisResult: '載入這筆結果',
    deleteThisResultTitle: '刪除這筆結果',
    candles: 'K 線',
    volume: '成交量',
    entry: '進場',
    exit: '出場',
    tradesLegend: '交易',
    notLoadedYet: '尚未載入。',
    loading: '載入中...',
    noDataAvailable: '沒有可用資料',
    failedToLoadData: '載入資料失敗',
    unknown: '未知',
    longEntrySignals: '多單進場訊號',
    longExitSignals: '多單出場訊號',
    shortEntrySignals: '空單進場訊號',
    shortExitSignals: '空單出場訊號',
    longEntry: '多單進場',
    longExit: '多單出場',
    shortEntry: '空單進場',
    shortExit: '空單出場',
    spinning: '載入中',
    longerThanExpectedHoldOn: '這比預期花更久，請稍候。',
    pairLabel: '交易對',
    walletHistory: '錢包歷史',
    cumulativeProfit: '累積獲利',
    botComparison: '機器人比較',
    openTradesWidget: '未平倉交易',
    closedTradesWidget: '已平倉交易',
    profitOverTime: '獲利隨時間變化',
    combined: '合併',
    useLiveDataHint: '僅在本機沒有下載資料時才使用。',
    freqtradeDocumentation: 'Freqtrade 文件',
  },
  en: {},
} as const;

const englishOverrides: Record<string, string> = {
  appTitle: 'Freqtrade UI',
  apiUrl: 'API URL',
  uiSettings: 'UI Settings',
  chartSettings: 'Chart Settings',
  notificationSettings: 'Notification Settings',
  backtestingSettings: 'Backtesting Settings',
  botListExpired: 'Login info expired!',
  botLoginHeader: 'Login to your bot',
  availableBotsTitle: 'Available bots',
  openTradesTitle: 'Open trades',
  tradeHistoryTitle: 'Trade history',
  noOpenTrades: 'No open trades.',
  noClosedTradesSoFar: 'No closed trades yet.',
  openTradesHint:
    'Shows the open trades for all selected bots. Click a trade to open the trade / bot trade page.',
  closedTradesHint:
    'Shows the closed trades for all selected bots. Click a trade to open the trade / bot trade page.',
  noTradesToShow: 'No trades to show.',
  settingsPanel: 'Settings',
  loadHistoricResults:
    'Load historic results from disk. You can click multiple results to load them into freqUI.',
  deleteResult: 'Delete result',
  deleteResultFromDisk: 'Delete result {{filename}} from disk?',
  refreshResults: 'Refresh results',
  filterResults: 'Filter results',
  strategyLabel: 'Strategy',
  detailsLabel: 'Details',
  backtestTime: 'Backtest time',
  filename: 'Filename',
  loadThisResult: 'Load this result',
  deleteThisResultTitle: 'Delete this result',
  itemsSelected: '{0} items selected',
  noSelectedItem: 'No selected item',
  deleteThisValue: 'Delete this value',
  addNewValue: 'Add new value',
  toggleNightMode: 'Toggle night mode',
  drawer: 'Drawer',
  autoRefresh: 'Auto refresh',
  autoRefreshAllNow: 'Refresh all bots now',
  type: 'Type',
  color: 'Color',
  lineChart: 'Line chart',
  barChart: 'Bar chart',
  scatterChart: 'Scatter chart',
  areaChartFillTo: 'Area chart - Fill to (leave empty for line chart)',
  scatterSymbolSize: 'Scatter symbol size',
  noStrategySelectedCannotLoadPlotConfig: 'No strategy selected, cannot load plot config.',
  failedToLoadPlotConfigFromStrategy: 'Failed to load plot configuration from strategy.',
  deleteThis: 'Delete this {{name}}',
  duplicateThis: 'Duplicate this {{name}}',
  editThis: 'Edit this {{name}}',
  addNewThis: 'Add new {{name}}',
  abort: 'Cancel',
  ok: 'OK',
  defaultsTo: 'Defaults to',
  notAvailableInThisChart: 'not available in this chart',
  language: 'Language',
  english: 'English',
  traditionalChinese: 'Traditional Chinese',
};

function humanizeKey(key: string) {
  const spaced = key
    .replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replaceAll(/[_-]+/g, ' ')
    .trim();

  return spaced
    .split(/\s+/)
    .map((word) => {
      const lower = word.toLowerCase();
      if (lower === 'api') return 'API';
      if (lower === 'ui') return 'UI';
      if (lower === 'url') return 'URL';
      if (lower === 'id') return 'ID';
      if (lower === 'cors') return 'CORS';
      if (lower === 'ft') return 'FT';
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}

type Locale = keyof typeof translations;
type TranslationKey = keyof (typeof translations)['zh-TW'];
type TranslationParams = Record<string, string | number>;

export function useUiText() {
  const locale = useLocalStorage<Locale>('frequi-locale', 'en');

  const t = (key: TranslationKey | string, params?: TranslationParams) => {
    const active = translations[locale.value] ?? translations.en;
    const text =
      (locale.value === 'en'
        ? englishOverrides[key] ?? humanizeKey(key)
        : (active as Record<string, string>)[key] ??
          englishOverrides[key] ??
          humanizeKey(key)) ?? key;
    if (!params) {
      return text;
    }
    return Object.entries(params).reduce(
      (acc, [paramKey, value]) => acc.replaceAll(`{{${paramKey}}}`, String(value)),
      text,
    );
  };

  const currentLocale = computed(() => locale.value);

  return {
    locale,
    currentLocale,
    t,
  };
}
